/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chat_dim_ecc_Secp256k1 */

#ifndef _Included_chat_dim_ecc_Secp256k1
#define _Included_chat_dim_ecc_Secp256k1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chat_dim_ecc_Secp256k1
 * Method:    makeKeys
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_chat_dim_ecc_Secp256k1_makeKeys
  (JNIEnv *, jclass);

/*
 * Class:     chat_dim_ecc_Secp256k1
 * Method:    computePublicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_chat_dim_ecc_Secp256k1_computePublicKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     chat_dim_ecc_Secp256k1
 * Method:    verify
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_chat_dim_ecc_Secp256k1_verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     chat_dim_ecc_Secp256k1
 * Method:    sign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_chat_dim_ecc_Secp256k1_sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
