/* license: https://mit-license.org
 *
 *  DIM-SDK : Decentralized Instant Messaging Software Development Kit
 *
 *                                Written in 2019 by Moky <albert.moky@gmail.com>
 *
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
package chat.dim.core;

import chat.dim.protocol.ID;
import chat.dim.protocol.Message;
import chat.dim.protocol.SymmetricKey;

/**
 *  Delegate interface for managing <b>directional symmetric encryption keys</b> in messaging.
 *  <p>
 *      Core concept: Symmetric keys are direction-specific (unidirectional) between two parties:
 *      - User A &rarr; User B: Uses key1 (generated by A, for A&rarr;B messages only)
 *      - User B &rarr; User A: Uses key2 (generated by B, for B&rarr;A messages only)
 *      - Key1 &ne; Key2, both exist simultaneously during A&harr;B communication
 *      - Independent key pairs are generated for A&harr;C, B&harr;C, etc.
 *  </p>
 *  <p>
 *      Key features:
 *      1. Directionality: Keys are scoped to (sender &rarr; receiver) pairs (not bidirectional)
 *      2. Reusability: Cached keys can be reused for subsequent messages in the same direction
 *      3. Context awareness: Handles personal/group/broadcast message key management
 *  </p>
 */
public interface CipherKeyDelegate {

    /*  Message scenario matrix (key destination determination):

                      +-------------+-------------+-------------+-------------+
                      |  receiver   |  receiver   |  receiver   |  receiver   |
                      |     is      |     is      |     is      |     is      |
                      |             |             |  broadcast  |  broadcast  |
                      |    user     |    group    |    user     |    group    |
        +-------------+-------------+-------------+-------------+-------------+
        |             |      A      |             |             |             |
        |             +-------------+-------------+-------------+-------------+
        |    group    |             |      B      |             |             |
        |     is      |-------------+-------------+-------------+-------------+
        |    null     |             |             |      C      |             |
        |             +-------------+-------------+-------------+-------------+
        |             |             |             |             |      D      |
        +-------------+-------------+-------------+-------------+-------------+
        |             |      E      |             |             |             |
        |             +-------------+-------------+-------------+-------------+
        |    group    |             |             |             |             |
        |     is      |-------------+-------------+-------------+-------------+
        |  broadcast  |             |             |      F      |             |
        |             +-------------+-------------+-------------+-------------+
        |             |             |             |             |      G      |
        +-------------+-------------+-------------+-------------+-------------+
        |             |      H      |             |             |             |
        |             +-------------+-------------+-------------+-------------+
        |    group    |             |      J      |             |             |
        |     is      |-------------+-------------+-------------+-------------+
        |    normal   |             |             |      K      |             |
        |             +-------------+-------------+-------------+-------------+
        |             |             |             |             |             |
        +-------------+-------------+-------------+-------------+-------------+

        Scenario explanations:
          A: Personal message (1:1, directional key)
          B: (same to J)
          C: Broadcast to individual user (no encryption)
          D: (same to G)
          E: Broadcast group message to individual user (no encryption)
          F: Broadcast group message to any user (no encryption)
          G: Broadcast group message (receiver=group, no encryption, non-split)
          H: Group message targeted to individual member (split key)
          J: Standard group message (receiver=group, non-split)
          K: Unencrypted group command (broadcast receiver + normal group)
     */

    /**
     *  Derives the key destination ID for a message (determines key scope).
     *  <p>
     *      Maps the message's receiver/group context to a standard destination ID
     *      for key lookup/caching (follows the scenario matrix above).
     *  </p>
     *
     * @param msg is the message to get key destination for.
     * @return the standardized destination ID for key management.
     */
    static ID getDestination(Message msg) {
        ID receiver = msg.getReceiver();
        ID group = ID.parse(msg.get("group"));
        return getDestination(receiver, group);
    }

    /**
     *  Core method to determine key destination ID from receiver/group context.
     *  <p>
     *      Handles scenario transformations:
     *      1. If group is null but receiver is group &rarr; map to group ID (B&rarr;J, D&rarr;G)
     *      2. If group is null &rarr; use receiver (personal/broadcast user message: A/C)
     *      3. If group is broadcast &rarr; use group ID (broadcast scenarios: E/F/G)
     *      4. If receiver is broadcast &rarr; use receiver (unencrypted group command: K)
     *      5. Otherwise &rarr; use group ID (standard group scenarios: H/J)
     *  </p>
     *
     * @param receiver is the target receiver ID (user/group/broadcast).
     * @param group is the optional group ID (null for personal messages).
     * @return the standardized destination ID for key management.
     * @throws AssertionError if ID types are invalid (e.g., non-user receiver for personal message).
     */
    static ID getDestination(ID receiver, ID group) {
        if (group == null && receiver.isGroup()) {
            /// Transform:
            ///     (B) => (J)
            ///     (D) => (G)
            group = receiver;
        }
        if (group == null) {
            /// A : personal message (or hidden group message)
            /// C : broadcast message for anyone
            assert receiver.isUser() : "receiver error: " + receiver;
            return receiver;
        }
        assert group.isGroup() : "group error: " + group + ", receiver: " + receiver;
        if (group.isBroadcast()) {
            /// E : unencrypted message for someone
            //      return group as broadcast ID for disable encryption
            /// F : broadcast message for anyone
            /// G : (receiver == group) broadcast group message
            assert receiver.isUser() || receiver.equals(group) : "receiver error: " + receiver;
            return group;
        } else if (receiver.isBroadcast()) {
            /// K : unencrypted group message, usually group command
            //      return receiver as broadcast ID for disable encryption
            assert receiver.isUser() : "receiver error: " + receiver + ", group: " + group;
            return receiver;
        } else {
            /// H    : group message split for someone
            /// J    : (receiver == group) non-split group message
            return group;
        }
    }

    /**
     *  Retrieves the directional symmetric key for (sender &rarr; receiver) communication.
     *  <p>
     *      Key rules:
     *      - Returns the key specific to the sender&rarr;receiver direction (not reverse)
     *      - If key doesn't exist and {@code generate} is true &rarr; creates a new random key
     *      - If key doesn't exist and {@code generate} is false &rarr; returns null
     *  </p>
     *
     * @param sender is the source user/contact ID (defines key direction origin).
     * @param receiver is the target user/group ID (defines key direction target).
     * @param generate is whether to generate a new key if none exists.
     * @return the directional symmetric key for sender&rarr;receiver (null if not found and not generated).
     */
    SymmetricKey getCipherKey(ID sender, ID receiver, boolean generate);

    /**
     *  Caches a directional symmetric key for reuse in (sender &rarr; receiver) communication.
     *  <p>
     *      Key rules:
     *      - Stores the key under the exact (sender, receiver) pair (directional)
     *      - Overwrites any existing key for the same direction (sender&rarr;receiver)
     *      - Does not affect the reverse direction (receiver&rarr;sender) key
     *  </p>
     *
     * @param sender is the source user/contact ID (key direction origin).
     * @param receiver is the target user/group ID (key direction target).
     * @param key is the symmetric key to cache (must be unique for this direction).
     */
    void cacheCipherKey(ID sender, ID receiver, SymmetricKey key);
}
