/* license: https://mit-license.org
 *
 *  DIM-SDK : Decentralized Instant Messaging Software Development Kit
 *
 *                                Written in 2019 by Moky <albert.moky@gmail.com>
 *
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
package chat.dim.msg;

import chat.dim.protocol.ReliableMessage;


/**
 * Delegate interface for verifying ReliableMessage signatures.
 *
 * Handles the final verification step to convert ReliableMessage back to
 * SecureMessage by validating the sender's signature.
 */
public interface ReliableMessageDelegate/* extends SecureMessageDelegate*/ {

    /*
     *  Verify the Reliable Message to Secure Message
     *
     *    +-----------+      +----------+
     *    | sender    |      | sender   |
     *    | receiver  |      | receiver |
     *    | time      |  ->  | time     |
     *    |           |      |          |
     *    | data      |      | data     |  1. verify(data, signature, sender.PK)
     *    | keys      |      | keys     |
     *    | signature |      +----------+
     *    +-----------+
     */

    // -------------------------------------------------------------------------
    //  Verification Pipeline (Step 1-2)
    // -------------------------------------------------------------------------

    /*
     *  Decodes Base64 signature string to raw binary data (Step 1).
     *
     *  Converts the ReliableMessage's Base64-encoded 'signature' field back to
     *  raw binary signature data for verification.
     *
     *  @param signature the base64-encoded string of the signature
     *  @param rMsg      the parent reliable message object (context)
     *  @return the raw binary signature data (null if decoding fails)
     */
    //byte[] decodeSignature(Object signature, ReliableMessage rMsg);

    /**
     * Verifies encrypted content data against sender's signature (Step 2).
     *
     * Uses the sender's public key (from Meta/Visa) to validate that the
     * signature was generated by the sender's private key (authenticity check).
     *
     * @param data      the encrypted binary data of the content
     * @param signature the digital signature of the content data
     * @param rMsg      the parent reliable message object (context)
     * @return true if signature matches (authentic), false otherwise
     */
    boolean verifyDataSignature(byte[] data, byte[] signature, ReliableMessage rMsg);
}
